config/routes.rb
Rails.application.routes.draw do
  devise_for :clients
  get 'welcome/index'
  get 'sign_up' => 'clients#new', :as => 'sign_up'
  get 'auth/facebook', as: "auth_provider"
  get 'auth/facebook/callback', to: 'users#login'

  resources :clients

  root "welcome#index"

end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  def self.koala(auth)
    access_token = auth['token']
    facebook = Koala::Facebook::API.new(access_token)
    facebook.get_object("me?fields=name,picture")
  end
  
  attr_accessor :city
  attr_accessor :state
  
  before_save { self.email = email.downcase }
  validates :fname, length: {maximum: 25}
  validates :lname, length: {maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_uniqueness_of :email, presence: true, length: {maximum: 255},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }

  validates_confirmation_of :password
     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def  new
    @client = Client.new
  end
  
  def create
    @client = Client.new(client_params)
    
    if @client.save
      @client.save
      redirect_to @client
    else
      render "new"
    end
  end
  
  def show
    @client = Client.find(params[:id])
  end
  
  def index
    @clients = Client.all
  end
  
  def edit
    @client = Client.find(params[:id])
  end
  
  def update
          @client = Client.find(params[:id])
          
          if @client.update(client_params)
                  redirect_to @client
          else
                  render 'edit'
          end
  end
  
  def login
    @client = Client.koala(request.env['omniauth.auth']['credentials'])
    @client.save
  end
  
  private
    def client_params
      params.require(:client).permit(:fname, :lname, :email, :password, :password_confirmation, :city, :state)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/edit.html.erb
<html>
  <body>
      <div class="container-fluid">
        <div class="row">  
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <a class="btn btn-default" role="button" href="<%= clients_path %>">Back</a>
            </div>
            
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <h1>Edit</h1>
            
              <%= bootstrap_form_for :client, url: client_path(@client), method: :patch do |f| %>
                  <% if @client.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@client.errors.count, "error") %> prohibited
                    this client from being created:</h2>
                  
                    <ul>
                    <% @client.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                    </ul>
                  </div>
                  <% end %>
                <div class="col-lg-6">
                  <p>
                    <%= f.text_field :fname, label: "First Name", placeholder: "First Name" %>
                  </p>
                  <p>
                    <%= f.text_field :lname, label: "Last Name", placeholder: "Last Name" %>
                  </p>
                  <p>
                    <%= f.text_field :email, label: "Email", placeholder: "Email" %>
                  </p>
                </div>
                <div class="col-lg-6">
                  <p>
                    <%= f.text_field :password, type: "password", label: "New Password", placeholder: "Enter New Password" %>
                  </p>
                  <p>
                    <%= f.text_field :password_confirmation, type: "password", label: "Confirm Password", placeholder: "Confirm Password" %>
                  </p>
                </div>
                <p>
                  <%= f.submit "Update", class:"btn btn-primary" %>
                </p>
              <% end %>
            </div>
            
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            </div>  
        </div>
      </div>
  </body>     
</html>

app/views/clients/index.html.erb
<html>
  <head>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>
  <body>
    <div>
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
              <img alt="Gist" src="http://i.imgur.com/dcGnzPz.png" height="23.69" width="64.93">
            </a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
            <ul> 
              <button type="submit" class="nav navbar-nav btn btn-success pull-right"><i class="fa fa-power"> Logout</i></button>
            </ul> 
          </div><!--/.navbar-collapse -->
        </div>
      </nav>
    </div>
      <br>
      <br>
      <br>
  	      <div class="container-fluid">
		<div class="row">
			<div class="navbar navbar-default sidebar col-sm-4 col-md-3 col-lg-3" role="navigation">
                          <ul class="nav">
                            <li class="sidebar-search">
                              <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                  <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                      <i class="fa fa-search"></i>
                                    </button>
                                  </span>
                              </div>
                            </li>
                            <li><a href="#">Dashboard</a></li>
                            <li><a href="#">Clients</a></li>
                            <li><a href="#bonuses">Bonuses</a></li>
                            <li><a href="#contact">Premiums</a></li>
			    <li><a href="#contact">Premiums</a></li>
			    <li><a href="#contact">Premiums</a></li>
			    <li><a href="#contact">Premiums</a></li>
			    <li><a href="#contact">Premiums</a></li>
			    <li><a href="#contact">Premiums</a></li>
			    <li><a href="#contact">Premiums</a></li>
			    <li><a href="#contact">Premiums</a></li>
			    <li><a href="#contact">Premiums</a></li>
                          </ul>
                        </div>
			
		        
		      <div class="container">
			<!-- Client Alert -->
			<div class="row">
			  <div class="col-sm-6 col-md-6 col-lg-3">
			    <div class="panel panel-primary">
			      <div class="panel-heading">
				<i class="fa fa-users fa-5x"></i> <i class="fa fa-plus fa-3x"></i>
				  <h5>
				    5 new clients!
				  </h5>
				
			      </div>
			    </div>
			  </div>
			
			<!-- Notification Alert -->
			<div class="row">
			  <div class="col-sm-6 col-md-6 col-lg-3">
			    <div class="panel panel-success">
			      <div class="panel-heading">
				<i class="fa fa-exclamation-circle fa-5x">
				  <h5>
				    2 new notifications!
				  </h5>
				</i>
			      </div>
			    </div>
			  </div>
			  
			<!-- Notification Alert -->
			<div class="row">
			  <div class="col-sm-6 col-md-6 col-lg-3">
			    <div class="panel panel-info">
			      <div class="panel-heading">
				<i class="fa fa-envelope fa-5x">
				  <h5>
				    3 new messages!
				  </h5>
				</i>
			      </div>
			    </div>
			  </div>
			  
			  <!-- Client Table -->
			  <div class="row">
			    <div class="col-sm-6 col-md-6 col-lg-6">
				    <div class="panel panel-primary">
					    <div class="panel-heading">Clients</div>
						    <div class="panel-body">
							    <p>
								    Take a look at all of the clients in the system. Enjoy!
							    </p>
						    </div>
					    <table class="table table-hover table-responsive"> 
						    <tr class="default">
							    <th>First Name</th>
							    <th>Last Name</th>
							    <th>Email</th>
							    <th></th>
							    <th></th>
    
						    </tr>
					    
						    <% @clients.each do |client| %>
							    <tr>
								    <td><%= client.fname %></td>
								    <td><%= client.lname %></td>
								    <td><%= client.email %></td>
								    <td><%= link_to 'Show', client_path(client) %></td>
								    <td><%= link_to 'Edit', edit_client_path(client) %></td>
							    </tr>
						    <% end %>
					    </table>
				    </div>
			    </div>
			  </div>
			  </div>
			</div>
		</div>
	      </div>
  
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/clients/login.html.erb
<%= image_tag @client['picture']['data']['url'.to_s] %>
<%= @user['name'] %>

app/views/clients/new.html.erb
<html>
  <body background="http://i.imgur.com/FSYe5Xt.jpg" style="background-position: right top;">
    
    <!-- JavaScript to load Facebook SDK
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '843424195701550',
          xfbml      : true,
          version    : 'v2.1'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script> -->
    
    <div>
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
              <img alt="Gist" src="http://i.imgur.com/dcGnzPz.png" height="23.69" width="64.93">
            </a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
            <form class="navbar-form navbar-right hidden-xs" role="form">
              <div class="form-group">
                <input type="text" placeholder="Email" class="form-control">
              </div>
              <div class="form-group">
                <input type="password" placeholder="Password" class="form-control">
              </div>
              <button type="submit" class="btn btn-success">Sign in</button>
            </form>
            <!--<button type="submit" class="btn btn-primary"
                    onclick="FB.getLoginStatus(function(response) {
                              if (response.status === 'connected') {
                                console.log('Logged in.');
                              }
                              else {
                                FB.login();
                              }
                            });"> <i class="fa fa-facebook"> Login with Facebook</i></button>-->
          </div><!--/.navbar-collapse -->
        </div>
      </nav>
    </div>
      <br>
      <br>
      <br>
      <!-- Container for registration form -->
      <div class="container">
        <!-- Row for registration form-->
        <div class="row">
          <!-- Column for quote -->
          <div class=" col-md-8 col-lg-8">
            <blockquote>
              <p>This could change the health insurance industry forever.</p>
              <footer>Flow from <cite title="Source Title">Progressive</cite></footer>
            </blockquote>
          </div>
          <!-- Column for registration form -->
          <div class="col-sm-12 col-md-12 col-lg-4">
            <div class="panel panel-default">
              <div class="panel-body">
                <h1>Create <small>New Account</small></h1>
                
                <%= bootstrap_form_for :client, url: clients_path do |f| %>

                <p>
                  <%= f.text_field :fname, label: "First Name:", placeholder: "First Name", autofocus: true  %>
                </p>
                
                <p>
                  <%= f.text_field :lname, label: "Last Name", placeholder: "Last Name" %>
                </p>
               
                <p>
                  <%= f.email_field :email, prepend: "@", label: "Email", placeholder: "Email"%>
                </p>
                
                <p>
                  <%= f.password_field :password, label: "Password", placeholder: "Password", help: "Must be at least 6 characters long" %>
                </p>
                
                <p>
                  <%= f.password_field :password_confirmation, class: "has-warning", label: "Confirm Password", placeholder: "Confirm Password" %>
                </p>
                
                <p>
                  <%= f.submit "Create", class: "btn btn-success btn-md" %>
                </p>
              <% end %>
            </div>
          </div> <!-- Panel for registration form-->
        </div> <!-- Column for registration form -->
      </div> <!-- Row for registration form-->
      <footer>
        <!--<div
          class="fb-like"
          data-send="true"
          data-width="450"
          data-show-faces="true"
          data-layout="standard">
        </div>-->
      </footer>
    </div> <!-- Container for registration form -->
  </body>
</html>

app/views/clients/show.html.erb
<html>
  <body>
    <div>
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
              <img alt="Gist" src="http://i.imgur.com/dcGnzPz.png" height="23.69" width="64.93">
            </a>
          </div>
          <div id="navbar" class="nav navbar-top-links navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="<%= @client_path %>">Home</a></li>
            </ul>
            <ul class="nav navbar-nav pull-right"><li class=""><a href="#"><i class="fa fa-power-off"> Log Out</i></a>
            </ul>
            <!-- Don't need on this page
            <form class="navbar-form navbar-right hidden-xs" role="form">
              <div class="form-group">
                <input type="text" placeholder="Email" class="form-control">
              </div>
              <div class="form-group">
                <input type="password" placeholder="Password" class="form-control">
              </div>
              <button type="submit" class="btn btn-success">Sign in</button>
            </form> -->
          
          </div><!--/.navbar-collapse -->
        </div>
      </nav>
    </div>
      <br>
      <br>
      <br>
      <br>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <i class="fa fa-user fa-5x">
                <h1>
                  <%= @client.fname %> <small><%= @client.lname %> </small> 
                  <small><%= link_to 'Edit', edit_client_path(@client) %></small>
                </h1>
              </i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-12">
              <div class="tabpanel" role="tablist">
                <ul class="nav nav-pills nav-justified fa-ul">
                  <li role="presentation" class="active"><a href="#overview" role="pill" aria-controls="overview" data-toggle="pill"><i class="fa fa-dashboard"></i>Overview</a></li>
                  <li role="presentation"><a href="#info" role="pill" aria-controls="info" data-toggle="pill"><i class="fa fa-info-circle"></i>Info</a></li>
                  <li role="presentation"><a href="#data" role="pill" aria-controls="data" data-toggle="pill"><i class="fa fa-bar-chart"></i>Data</a></li>
                </ul>
              </div>
          </div>
        </div>
              
            <div class="tab-content">
              <div role="pillpanel" class="tab-pane fade in active" id="overview">
                <br>
                <div class="row">
                  <div class="col-sm-10 col-md-10 col-lg-10">
                    <div class="panel panel-default">
                      <div class="panel-heading"><h2>Bonus <small>Progress</small></h2></div>
                        <div class="panel-body">
                          <p>
                            <div class="progress">
                              <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
                                <span class="sr-only">45% Complete</span>
                              </div>
                            </div>
                            <h4>Burn 1000 more calories this month to qualify for our January bonus!</h4>
                          </p>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
            
              <!--Info Panel -->
              <br>
                <div role="pillpanel" class="tab-pane fade" id="info">
                  <div class="col-sm-6 col-md-4 col-lg-4">
                    <div class="panel panel-default">
                      <div class="panel-heading"><h3>Contact <small>Me</small></h3></div>
                      <div class="panel-body">
                        <p>
                          <strong>Email:</strong>
                          <%= @client.email %>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              
              <!-- Data Panel-->
              <div role="pillpanel" class="tab-pane fade panel panel-default" id="data">
                <br>
                <div class="row">
                  <div class="col-sm-12 col-md-6 col-lg-6">
                    
                    <!-- Calories Panel -->
                    <div class="panel panel-default">
                      <div class="panel-heading">Calories</div>
                        <div class="panel-body"> fdsagdasgg</div>  
                          <table class="table table-hover table-responsive">
                            <tr>
                              <th>Sunday</th>
                              <th>Monday</th>
                              <th>Tuesday</th>
                              <th>Wednesday</th>
                              <th>Thursday</th>
                              <th>Friday</th>
                              <th>Saturday</th>
                            </tr>
                            <tr>
                              <td>1040</td>
                              <td>560</td>
                              <td>250</td>
                              <td>720</td>
                              <td>860</td>
                              <td>1215</td>
                              <td>1416</td>
                            </tr>
                          </table>
                    </div>
                  </div>
                </div>  
              </div>
            </div> <!-- Tab Contect -->
      </div>   
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seniorproject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<footer>
  <div class="notice"><%= notice %></div>
  <div class="alert alert-warning" role="alert"><%= alert %></div>
</footer>
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Gist</title>

    <!-- Bootstrap core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <div>
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
              <img alt="Gist" src="http://i.imgur.com/dcGnzPz.png" height="23.69" width="64.93">
            </a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
            <form class="navbar-form navbar-right hidden-xs" role="form">
              <div class="form-group">
                <input type="text" placeholder="Email" class="form-control">
              </div>
              <div class="form-group">
                <input type="password" placeholder="Password" class="form-control">
              </div>
              <button type="submit" class="btn btn-default">Login</button>
              <span <h2>or</h2></span>
              <button type="button" class="btn btn-default btn-sm"><i class="fa fa-facebook-square fa-2x"></i></button>
            
            </form>
          </div><!--/.navbar-collapse -->
        </div>
      </nav>
    </div>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <br>
        <br>
        <h1>Savings You Deserve</h1>
        <p>Active people get great rates with Gist. Bridge the gap between you and your health insurance provider and earn savings you deserve for living a healthy lifestyle! Use your favorite wearable fitness device to save on premiums and qualify for health insurance bonuses!</p>
        <p><a class="btn btn-success btn-lg" href="<%= new_client_path %>" role="button">Let's Get Started</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Wear</h2>
          <p>Select a fitness device of your choice. Gist is compatible with two different fitness tech companies: Fitbit and Jawbone.</p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Move</h2>
          <p>The more you move, the more you save. Rack up the miles and calories burned and start saving today! Living an active healthy lifestyle is the key great rates!</p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Save</h2>
          <p>A number of health insurance companies have provided several savings options for when you meet your fitness goals. Track your fitness progress and see how close you are to earning your next bonus!</p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p><i class="fa fa-copyright fa-1x"> Gist 2014</i>
          <i class="fa fa-instagram pull-right" href="http://www.instagram.com"></i>
          <i class="fa fa-twitter pull-right" href="http://www.twitter.com"></i>
          <i class="fa fa-facebook pull-right" href="http://www.facebook.com"></i>
        </p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>